# Class 7: Introduction to NumPy

**Objective**: Learn how to use NumPy for numerical data, including creating arrays, performing operations, indexing, and understanding broadcasting.

**Topics**:
- What is NumPy?
- Creating arrays (1D, 2D, zeros, ones, random)
- Array operations (addition, multiplication, etc.)
- Indexing and slicing
- Broadcasting basics

This notebook includes explanations, examples, and exercises to help you get comfortable with NumPy. Follow along, run the code, and try the exercises!

## 1. What is NumPy?

NumPy is a Python library for numerical computing. It’s fast, efficient, and great for working with arrays (like lists, but better for math). Think of it as a toolbox for handling numbers, matrices, and data in AI projects.

Let’s start by importing NumPy. Run the cell below:

In [1]:
import numpy as np

## 2. Creating Arrays

Arrays are the core of NumPy. They can be 1D (like a list) or 2D (like a table/matrix). Let’s create some arrays.

### Example 1: 1D and 2D Arrays

In [2]:
# 1D array (like a list)
arr1 = np.array([1, 2, 3, 4])
print("1D array:", arr1)

# 2D array (like a matrix)
arr2 = np.array([[1, 2], [3, 4]])
print("2D array:\n", arr2)

1D array: [1 2 3 4]
2D array:
 [[1 2]
 [3 4]]


### Example 2: Special Arrays
NumPy has shortcuts for common arrays like zeros, ones, or random numbers.

In [3]:
# Array of zeros (2 rows, 3 columns)
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

# Array of ones
ones = np.ones((2, 2))
print("Ones:\n", ones)

# Random integers between 0 and 9 (3x2 array)
random_arr = np.random.randint(0, 10, size=(3, 2))
print("Random:\n", random_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Random:
 [[0 1]
 [4 0]
 [2 4]]


**Quick Check**: What does `size=(3, 2)` mean in the random array above? (Answer in your head: 3 rows, 2 columns!)

## 3. Array Operations

NumPy makes math easy. You can add, multiply, or even compute dot products on arrays.

### Example 3: Basic Operations

In [4]:
# Create two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", a + b)

# Multiplication (element-wise)
print("Element-wise multiplication:\n", a * b)

# Multiply by a number
print("Multiply by 2:\n", a * 2)

Addition:
 [[ 6  8]
 [10 12]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Multiply by 2:
 [[2 4]
 [6 8]]


### Example 4: Dot Product
The dot product is useful for matrix math (common in AI).
- The dot product (also known as matrix multiplication) is a way of combining two arrays (matrices or vectors) to get a new matrix.


✅ Formula (Matrix Multiplication Rule):
If a is a 2×2 matrix and b is also 2×2, then their dot product c = np.dot(a, b) is also 2×2.

To calculate each element of the resulting matrix:

Take a row from the first matrix a

Take a column from the second matrix b

Multiply corresponding elements and add them up

In [5]:
# Dot product of 2x2 matrices
dot_result = np.dot(a, b)
print("Dot product:\n", dot_result)

Dot product:
 [[19 22]
 [43 50]]


## 4. Indexing and Slicing

You can grab specific parts of an array, like picking a number or a row.

### Example 5: Accessing Elements

In [6]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", arr)

# Get element at row 1, column 2 (note: indexing starts at 0)
print("Element at [1, 2]:", arr[1, 2])  # Should be 60

# Get first row
print("First row:", arr[0, :])

# Get second column
print("Second column:", arr[:, 1])

Original array:
 [[10 20 30]
 [40 50 60]]
Element at [1, 2]: 60
First row: [10 20 30]
Second column: [20 50]


## 5. Broadcasting

Broadcasting lets you operate on arrays of different sizes, like adding a number to every element.

### Example 6: Broadcasting

In [7]:
# Add 5 to every element
arr = np.array([[1, 2], [3, 4]])
print("Original:\n", arr)
print("Add 5:\n", arr + 5)

Original:
 [[1 2]
 [3 4]]
Add 5:
 [[6 7]
 [8 9]]


## Exercises

Now it’s your turn! Complete the exercises below to practice NumPy. Write your code in the cells provided, and run them to check your results.

**Exercise 1**: Create a 3x3 array of random integers between 1 and 10, then multiply it by 2.

In [13]:
# Your code here

# Create a 3x3 array of random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=(3, 3))

# Multiply every element by 2
result = arr * 2

print("Original Array:\n", arr)
print("After Multiplying by 2:\n", result)


Original Array:
 [[9 9 8]
 [3 6 2]
 [3 6 9]]
After Multiplying by 2:
 [[18 18 16]
 [ 6 12  4]
 [ 6 12 18]]


**Exercise 2**: Create a 4x2 array of zeros, then set the second row to [9, 9].

In [14]:
# Your code here
# Create a 4x2 array of zeros
arr = np.zeros((4, 2), dtype=int)

# Set the second row (index 1) to [9, 9]
arr[1] = [9, 9]

print(arr)


[[0 0]
 [9 9]
 [0 0]
 [0 0]]


**Exercise 3**: Given the array below, extract the first column and compute its sum.

In [10]:
# Provided array
ex3_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", ex3_arr)

# Your code here



Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Exercise 4**: Add the two arrays below and print the result.

In [11]:
# Provided arrays
arr_a = np.array([[1, 1], [2, 2]])
arr_b = np.array([[3, 3], [4, 4]])

# Your code here



## Mini-Project Preview

Later this week, you’ll work with the Iris dataset (a table of flower measurements). NumPy will help us do math on the data, like computing averages or scaling values. For now, think about what kinds of numbers you might want to analyze (e.g., petal lengths). No code yet—just something to ponder!

**Quick Question**: If petal lengths were in an array like `[5.1, 4.9, 5.0]`, how could you compute their average using NumPy? (Hint: There’s a function for that! Try it below if you’re curious.)

In [12]:
# Optional: Try computing the average of [5.1, 4.9, 5.0]



## Wrap-Up

Great job! You’ve learned how to:
- Create NumPy arrays (1D, 2D, zeros, random).
- Perform operations like addition and multiplication.
- Index and slice arrays to get specific parts.
- Use broadcasting to simplify math.

Save this notebook and share your exercise results with the instructor if asked. Next class, we’ll dive into pandas for working with datasets!